### ISSUE TITLE
Unable to serve files from a symlink

### ISSUE THREAD

**Issue by Bekreth** [ebraminio/pad.js#20]
I have a project where some of the files are being referenced into my local path by symlink, and pad.js is unable to serve that content

**Comment by ebraminio** [comment]
Hi. Thanks for even using this project! Over the years I was thinking I'm the only user of this, knowing someone at least uses it gives motivation for working more on it.

About the particular issue, this is coming from `fs.realpathSync(path.replace(/[^\/\\]+$/, '')) + nativePathSep).indexOf(cwd) !== 0`, apparently I was worried that someone could use tricks using two dots '..' to access not shared folders and maybe tricks with links that's why I tried to be more careful, I don't claim this is the best or even a correct approach just that it needs more considerations if I want just to remove this bit altogether so instead added a `--follow-outside-links` option and made a release for it so you can test.

Thanks 😊

**Comment by Bekreth** [comment]
Wow, thanks for such a fast turnaround!  To give you a little detail about the "type" of person using your project, I've been messing around with HTMX lately for something that I plan on deploying to S3 as a static site.  I had to hunt around for a while to find something installable through NPM that just covered the "let me do POST requests" type of file server.  This really freed up a headache for me, so thank you for your project!
